### ISSUE TITLE
slkbuild.SlackBuild

### ISSUE THREAD

**Issue by GreenLunar** [gapan/slkbuild#6]
Please provide a build script for slkbuild.

**Comment by gapan** [comment]
Why? I don't see the point. There is already an SLKBUILD file here for example:
http://download.salixos.org/x86_64/14.2/source/d/slkbuild/SLKBUILD

**Comment by GreenLunar** [comment]
I meant to a SlackBuild build script for the Slackware fanatics. It would not harm, I guess.

**Comment by gapan** [comment]
You can get a package already built here if you want it:
http://download.salixos.org/x86_64/14.2/salix/d/slkbuild-1.2-noarch-1gv.tgz

No need for a SlackBuild script to build one. The only reason to create one would be for slkbuild to be part of SBo somehow, but I don't think they are interested in that.

**Comment by GreenLunar** [comment]
> No need for a SlackBuild script to build one. The only reason to create one would be for slkbuild to be part of SBo somehow, but I don't think they are interested in that.

You will never know, unless a SlackBuild build script would be provided.
