### ISSUE TITLE
SLKBUILD under /usr/doc/

### ISSUE THREAD

**Issue by GreenLunar** [gapan/slkbuild#7]
I suggest to locate SLKBUILD build scripts under `/usr/doc/`, not under `/usr/src/`.

By the way, Is there a configuration option to change`/usr/src/` to `/usr/doc/`?

**Comment by gapan** [comment]
No. /usr/doc is for documentation. These are not documentation files.

**Comment by GreenLunar** [comment]
I think that build scripts are suitable to be considered as documentation files.

But, assuming that you are correct, locating SLKBUILD build scripts under `/usr/src/` would likely be the first reason to discourage Slackware users to adopt SLKBUILD.

Even if I would have agreed with you, I would still be in favor of locating build scripts under `/usr/doc/`; that is to say, "reinventing the wheel" is not a good approach.

If you think otherwise, I think that you should refer to SBo; and once SBo would locate SlackBuild build scripts and patches under `/usr/src/`, only then the current state of SLKBUILD would be proper.

Please take this into consideration.

**Comment by GreenLunar** [comment]
```
--- /1/slkbuild
+++ /2/slkbuild
@@ -485,8 +485,8 @@
 }
 
 copy_build_script() {
-    mkdir -p $startdir/pkg/usr/src/$pkgname-$pkgver/
-    [ -f $startdir/SLKBUILD ] && cp $startdir/SLKBUILD    $startdir/pkg/usr/src/$pkgname-$pkgver/SLKBUILD
+    mkdir -p $startdir/pkg/usr/doc/$pkgname-$pkgver/
+    [ -f $startdir/SLKBUILD ] && cp $startdir/SLKBUILD    $startdir/pkg/usr/doc/$pkgname-$pkgver/SLKBUILD
 }
 
 create_package() {
@@ -587,7 +587,7 @@
 prepare_directory() {
     NOSRCPACK="$NOSRCPACK"
     mkdir \$startdir/src
-    mkdir -p \$startdir/pkg/usr/src/\$pkgname-\$pkgver
+    mkdir -p \$startdir/pkg/usr/doc/\$pkgname-\$pkgver
     for SOURCES in \${source[@]}; do
         protocol=\$(echo \$SOURCES | sed 's|:.*||')
             file=\$(basename \$SOURCES | awk -F= '{print \$NF}')
@@ -607,7 +607,7 @@
         cp -LR \$file \$startdir/src
         if ! [ "\$protocol" = "http" -o "\$protocol" = "https" -o "\$protocol" = "ftp" ]; then
             if ! [[ \$NOSRCPACK -eq 1 ]]; then
-                cp -LR \$startdir/\$(basename \$SOURCES) \$startdir/pkg/usr/src/\$pkgname-\$pkgver/
+                cp -LR \$startdir/\$(basename \$SOURCES) \$startdir/pkg/usr/doc/\$pkgname-\$pkgver/
             fi
         fi
     done
```
